- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: golang
  ansible.builtin.import_role:
    name: common
    tasks_from: golang

- name: system start
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd